# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        
    - uses: nttld/setup-ndk@v1
      with:
        ndk-version: r25c
        
    - name: Check Envirometn ANDROID_NDK_HOME
      run: echo $ANDROID_NDK_HOME && echo $ANDROID_HOME && echo $ANDROID_SDK_ROOT
    - name: Installing Gomobile
      run: go install golang.org/x/mobile/cmd/gomobile@latest

    - name: Go init
      run: gomobile init
      
    - name: Downloading Package Required
      run: go mod tidy
      
    - name: Go Install Binding
      run: go get golang.org/x/mobile/bind
      
    - name: Create AAR Folder build
      run: mkdir ./arr 
      
    - name: Build to Android Archive File
      run: gomobile bind -v -o ./arr/android.aar -androidapi 19 ./cmd

    - uses: actions/upload-artifact@v3
      with:
        name: BugScannergo (AAR)
        path: ./arr/android.aar
      
